version: '3.8'

services:
  frontend:
    container_name: anker-frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend-new:/app
      - /app/node_modules