name: Build and Push Docker Image

on:
  push:
    branches: [ "frontend-new-exp" ]

jobs:
  build-and-push:
    runs-on: ubuntu

    steps:
      # Checks out your repository code so the workflow can access it
      - name: Check out the repo
        uses: actions/checkout@v4

      # Sets up Docker Buildx, a modern builder that enables caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Logs into Docker Hub using the secrets we created earlier
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/unmute:latest,${{ secrets.DOCKERHUB_USERNAME }}/unmute:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tmpfs: /tmp